version: "3.9"
services:

  keycloak:
    image: jboss/keycloak
    ports: [ "8080:8080" ]
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
      KEYCLOAK_IMPORT: "/tmp/save/serious-realm.json"
    volumes:
      - "./save:/tmp/save"
    networks:
      default:
        aliases:
          - localtest.me

  gatekeeper:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.3
    ports: [ "4180:4180" ]
    restart: unless-stopped
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: "0.0.0.0:4180"
      OAUTH2_PROXY_COOKIE_SECRET: "OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w="
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"
      OAUTH2_PROXY_COOKIE_SECURE: "false"
      OAUTH2_PROXY_UPSTREAMS: "http://demo:80"
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"

      OAUTH2_PROXY_CLIENT_ID: "demo"
      OAUTH2_PROXY_CLIENT_SECRET: "o8P5TeKtFVTpYXzYAQ75lP0HnonKjWIO"
      OAUTH2_PROXY_REDIRECT_URL: "http://localtest.me:4180/oauth2/callback"

      OAUTH2_PROXY_WHITELIST_DOMAINS: "localtest.me:*"
      OAUTH2_PROXY_OIDC_ISSUER_URL: "http://localtest.me:8080/auth/realms/serious-realm"
      OAUTH2_PROXY_PROVIDER: "oidc"

    depends_on: [ "keycloak" ]

  demo:
    image: hypoport/httpd-cgi
    ports: [ "8180:80" ]
    volumes:
      - "./scripts:/usr/local/apache2/cgi-bin"
      - "./vendor:/usr/lib/perl5/vendor_perl"

